### ISSUE TITLE
Inventory Refresh Tracking 

### ISSUE THREAD

**Issue by slemrmartin** [RedHatInsights/topological_inventory-persister#52]
TPINVTRY-837

Link collected items to the `RefreshStatePart` model
- [x] https://github.com/RedHatInsights/topological_inventory-core/pull/183

Collect timestamps from beginning of collecting to the end in a persister
- [x] https://github.com/ManageIQ/inventory_refresh/pull/91
- [x] https://github.com/RedHatInsights/topological_inventory-core/pull/186
- [x] https://github.com/RedHatInsights/topological_inventory-persister/pull/53
- [x] https://github.com/RedHatInsights/topological_inventory-ingress_api/pull/84
- [x] https://github.com/RedHatInsights/topological_inventory-ingress_api-client-ruby/pull/65
- [x] https://github.com/RedHatInsights/topological_inventory-providers-common/pull/15
- [x] https://github.com/RedHatInsights/topological_inventory-amazon/pull/59
- [x] https://github.com/RedHatInsights/topological_inventory-ansible_tower/pull/77
- [x] https://github.com/RedHatInsights/topological_inventory-azure/pull/21
- [x] https://github.com/RedHatInsights/topological_inventory-openshift/pull/119
